// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { resolve } from "node:path"
import { config } from "dotenv"
import { defineConfig, env } from "prisma/config"

config({ path: resolve(process.cwd(), ".env.local") })
config({ path: resolve(process.cwd(), ".env") })

export default defineConfig({
  schema: "prisma/schema",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: env("DATABASE_URL"),
  },
})
