export const CollaborationRole = {
    OWNER: "OWNER",
    AUTHOR: "AUTHOR",
    TRANSLATOR: "TRANSLATOR",
    PROOFREADER: "PROOFREADER",
    EDITOR: "EDITOR",
} as const

export const CollaborationPermission = {
    EBOOK_READ: "EBOOK_READ",
    EBOOK_UPDATE_METADATA: "EBOOK_UPDATE_METADATA",
    EBOOK_DELETE: "EBOOK_DELETE",
    CHAPTER_READ: "CHAPTER_READ",
    CHAPTER_CREATE: "CHAPTER_CREATE",
    CHAPTER_UPDATE: "CHAPTER_UPDATE",
    CHAPTER_DELETE: "CHAPTER_DELETE",
    SNAPSHOT_READ: "SNAPSHOT_READ",
    SNAPSHOT_CREATE: "SNAPSHOT_CREATE",
    SNAPSHOT_RESTORE: "SNAPSHOT_RESTORE",
    ASSET_UPLOAD: "ASSET_UPLOAD",
    ASSET_DELETE: "ASSET_DELETE",
    COVER_UPDATE: "COVER_UPDATE",
    COLLABORATOR_INVITE: "COLLABORATOR_INVITE",
    COLLABORATOR_REMOVE: "COLLABORATOR_REMOVE",
    ROLE_ASSIGN: "ROLE_ASSIGN",
} as const
