export const MAX_LENGTH = {
    USERNAME: 30,
    TITLE_EBOOK: 100,
    SHORT_DESCRIPTION_EBOOK: 500,
    SUBTITLE_EBOOK: 75,
    TITLE_CHAPTER: 100,
}

export const MIN_LENGTH = {
    USERNAME: 3,
    TITLE_EBOOK: 1,
    SHORT_DESCRIPTION_EBOOK: 10,
    SUBTITLE_EBOOK: 1,
    TITLE_CHAPTER: 1,
}

