export const VALIDATION_ERRORS = {
    // User validation errors
    USERNAME_REQUIRED: "USERNAME_REQUIRED",
    USERNAME_TOO_SHORT: "USERNAME_TOO_SHORT",
    USERNAME_TOO_LONG: "USERNAME_TOO_LONG",

    INVALID_EMAIL: "INVALID_EMAIL",

    // Ebook validation errors
    TITLE_REQUIRED: "TITLE_REQUIRED",
    TITLE_TOO_SHORT: "TITLE_TOO_SHORT",
    TITLE_TOO_LONG: "TITLE_TOO_LONG",
    SUBTITLE_TOO_SHORT: "SUBTITLE_TOO_SHORT",
    SUBTITLE_TOO_LONG: "SUBTITLE_TOO_LONG",
    SHORT_DESCRIPTION_TOO_SHORT: "SHORT_DESCRIPTION_TOO_SHORT",
    SHORT_DESCRIPTION_TOO_LONG: "SHORT_DESCRIPTION_TOO_LONG",

    // Chapter validation errors
    CHAPTER_TITLE_REQUIRED: "CHAPTER_TITLE_REQUIRED",
    CHAPTER_TITLE_TOO_SHORT: "CHAPTER_TITLE_TOO_SHORT",
    CHAPTER_TITLE_TOO_LONG: "CHAPTER_TITLE_TOO_LONG",

} as const

export type ValidationErrorCode =
    typeof VALIDATION_ERRORS[keyof typeof VALIDATION_ERRORS];